# Generated by Django 5.1.6 on 2025-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
