# Generated by Django 5.1.6 on 2025-02-26 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0002_bannerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerevent',
            name='describe',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
