# Generated by Django 5.1.6 on 2025-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0003_alter_bannerevent_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstLocation',
            field=models.CharField(max_length=100, verbose_name='Lokasi Penjemputan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastLocation',
            field=models.CharField(max_length=100, verbose_name='Lokasi Tujuan'),
        ),
    ]
