# Generated by Django 5.1.6 on 2025-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0004_alter_order_firstlocation_alter_order_lastlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstLocation',
            field=models.CharField(max_length=255, verbose_name='Lokasi Penjemputan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastLocation',
            field=models.CharField(max_length=255, verbose_name='Lokasi Tujuan'),
        ),
    ]
