# Generated by Django 5.1.6 on 2025-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0005_alter_order_firstlocation_alter_order_lastlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Jarak (km)'),
        ),
    ]
