# Generated by Django 5.1.6 on 2025-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0006_order_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Harga Total'),
        ),
    ]
