# Generated by Django 5.1.6 on 2025-03-04 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omk', '0007_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Format: HH:MM', verbose_name='Waktu Jemput'),
            preserve_default=False,
        ),
    ]
